//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationSectionDesigner
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "csd";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Configuration Section Designer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Microsoft PLK";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ConfigurationSectionDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ConfigurationSectionDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ConfigurationSectionDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ConfigurationSectionDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewConfigurationSectionDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ConfigurationSectionDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string ConfigurationSectionDesignerPackageId = "9f16956e-2232-4f80-9ebb-4165929ef3ef";
		
		// Editor factory identifier
		public const string ConfigurationSectionDesignerEditorFactoryId = "548a5f67-a0b1-4c78-84f0-508456f45157";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ConfigurationSectionDesignerModelExplorerToolWindowId = "b5896815-b473-4bf5-b478-fe2b4252eb59";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace ConfigurationSectionDesigner
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ConfigurationSectionDesignerCommandSetId = "d6d3bd3e-6626-42d6-9428-e528e97848fa";
	}
}