//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace ConfigurationSectionDesigner
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class ConfigurationSectionDesignerExplorer : ConfigurationSectionDesignerExplorerBase
	{
		/// <summary>
		/// Constructs a new ConfigurationSectionDesignerExplorer.
		/// </summary>
		public ConfigurationSectionDesignerExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the ConfigurationSectionDesignerExplorerToolWindow.
	/// </summary>
	internal abstract class ConfigurationSectionDesignerExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new ConfigurationSectionDesignerExplorerBase.
		/// </summary>
		protected ConfigurationSectionDesignerExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::ConfigurationSectionDesigner.ConfigurationSectionDesignerDomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ConfigurationElement.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConfigurationElementExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ConfigurationElementCollection.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConfigurationElementCollectionExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ConfigurationSection.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConfigurationSectionExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.EnumerationLiteral.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnumerationLiteralExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.AttributeProperty.DomainClassId, 
							null, 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ElementProperty.DomainClassId, 
							null, 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.EnumeratedType.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnumeratedTypeExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ExternalType.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ExternalTypeExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ConfigurationSectionGroup.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConfigurationSectionGroupExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.ConfigurationSectionModel.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConfigurationSectionModelExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.PropertyValidators.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PropertyValidatorsExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.PropertyValidator.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PropertyValidatorExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ConfigurationSectionDesigner.CustomTypeConverter.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CustomTypeConverterExplorerImage")), 
							false); 
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.ConfigurationSectionDesignerExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::ConfigurationSectionDesigner.ConfigurationSectionModel.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
	}
}
	


